apiVersion: v1
kind: ConfigMap
metadata:
  name: postfix-init
data:
  10-nullclient.sh: |
    #!/bin/sh
    set -e
    postconf -e 'mydestination ='
    postconf -e 'local_transport = error:local delivery disabled'