apiVersion: apps/v1
kind: Deployment
metadata:
  name: smtp-relay
spec:
  replicas: 1
  selector:
    matchLabels: { app: smtp-relay }
  template:
    metadata:
      labels: { app: smtp-relay }
    spec:
      containers:
        - name: postfix
          image: boky/postfix:latest
          ports:
            - name: smtp
              containerPort: 25
          env:
            # identity & networks
            - name: HOSTNAME
              value: smtp-relay.ase-15.svc.cluster.local
            - name: POSTFIX_mynetworks
              value: "10.42.0.0/16, 10.43.0.0/16, 127.0.0.0/8"

            # relay to Gmail with AUTH
            - name: RELAYHOST
              value: "[smtp.gmail.com]:587"
            - name: RELAYHOST_USERNAME
              valueFrom: { secretKeyRef: { name: gmail-sasl, key: RELAYHOST_USERNAME } }
            - name: RELAYHOST_PASSWORD
              valueFrom: { secretKeyRef: { name: gmail-sasl, key: RELAYHOST_PASSWORD } }

            - name: ALLOWED_SENDER_DOMAINS
              value: "gmail.com"

            # null-client behavior + TLS/SASL knobs
            - name: POSTFIX_myorigin
              value: "$myhostname"
            - name: POSTFIX_mydestination
              value: ""
            - name: POSTFIX_local_transport
              value: "error:local delivery disabled"
            - name: POSTFIX_relay_domains
              value: "*"
            - name: POSTFIX_smtp_use_tls
              value: "yes"
            - name: POSTFIX_smtp_tls_security_level
              value: "encrypt"
            - name: POSTFIX_smtp_sasl_auth_enable
              value: "yes"
            - name: POSTFIX_smtp_sasl_security_options
              value: "noanonymous"
            - name: POSTFIX_smtp_sasl_tls_security_options
              value: "noanonymous"

            # rewrite envelope sender to your Gmail to keep Gmail happy :)
            - name: POSTFIX_smtp_generic_maps
              value: "regexp:/etc/postfix/generic"
          volumeMounts:
            - name: generic
              mountPath: /etc/postfix/generic
              subPath: generic
      volumes:
        - name: generic
          configMap:
            name: postfix-generic