apiVersion: v1
kind: Service
metadata:
  name: py-smtp-relay
  namespace: ase-15
spec:
  selector:
    app: py-smtp-relay
  ports:
    - name: smtp
      port: 25
      targetPort: 25
      protocol: TCP