name: Deploy

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest
    # if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Build and push image
        uses: Agile-Software-Engineering-25/build-and-publish-image@v1
        with:
          image_name: "py-smtp-relay"
          push: true
          extra_tags: ${{ github.sha }}
      - name: Deploy to k8s
        uses: Agile-Software-Engineering-25/deploy-to-k8s@v1
        with:
          kubeconfig: ${{ secrets.KUBECONFIG }}
          namespace: ${{ vars.K8S_NAMESPACE }}
